
SLANG_CLEAN_SEEDS = [
    "Selam, şifremi unuttum, tekrar nasıl oluşturabilirim?",
    "Teşekkürler, çok hızlı döndünüz, gerçekten memnun kaldım.",
    "Selam, uygulamaya giriş yapamıyorum, şifre yanlış diyor sürekli.",
    "Çok teşekkür ederim, artık her şey düzgün çalışıyor.",
    "Reis bu iş uzadı, bir an önce çözülmesini istiyorum açıkçası.",
    "Tamam anladım, peki bu işlem ne kadar sürer ortalama?",
    "Merhaba, adresimi güncellemem gerekiyor taşındığım için.",
    "Merhaba, ödemeyi kredi kartıyla yapabilir miyim acaba?",
    "Merhaba, hesabıma giriş yapınca hata veriyor sürekli.",
    "Selam nasılsın, bugün müsait misin bir kahve içelim?",
    "Kanka akşam maça geliyor musun, yoksa iş mi çıktı yine?",
    "Teşekkürler dostum, gerçekten iyi ki varsın, ödeşemem seninle.",
    "Merhaba, yarın buluşacak mıydık, saat kaçta nerede?",
    "Abi bu akşam bize gel, birlikte film izleriz güzelce.",
    "Selam, mesajını yeni gördüm, kusura bakma geç döndüm.",
    "Naber, uzun zamandır görüşemedik, bir ara toplanalım mı?",
    "Tamam anladım, o zaman yarın sabah ararım seni olur mu?",
    "Canım çok özledim seni, ne zaman geleceksin buraya?",
    "Hocam ödevi anlamadım, bir daha anlatır mısınız lütfen?",
    "Selam, yolda mısın, biz çoktan geldik seni bekliyoruz.",
    "Kanka bu çok komik ya, gülmekten karnım ağrıdı resmen.",
    "Merhaba, akşam yemeğe ne yapsak, canın ne çekiyor senin?",
    "Abi bir dakika bekle, hemen geliyorum aşağıya iniyorum.",
    "Selam, bu hafta sonu bir plan var mı, sıkıldım açıkçası.",
    "Teşekkür ederim, çok naziksin, Allah senden razı olsun.",
    "Naber kanka, dün neredeydin, seni her yerde aradım ama yoktun.",
    "Merhaba, param bitti bu ay, biraz borç verir misin acaba?",
    "Selam, sınav nasıl geçti, iyi miydi yoksa zor muydu çok?",
    "Abi telefonun kapalı sürekli, bir sorun mu var, merak ettim.",
    "Tamam görüşürüz o zaman, kendine iyi bak, yolda dikkatli ol.",
    "Selam, bugün hava çok güzel, bir yürüyüşe çıkalım mı beraber?",
    "Kanka o film gerçekten harikaymış, kesinlikle izlemelisin.",
    "Merhaba, doğum günün kutlu olsun, nice mutlu yıllara canım!",
    "Abi işler nasıl gidiyor, uzun zamandır haber alamadım senden.",
]

DIALECT_PAIRS = [
    ("uşağum naptun sen daha, celiy misun bu akşam bize", "Ne yaptın sen daha, geliyor musun bu akşam bize?"),
    ("da ne diyi bu adam ha, ben anlamadum haçan", "Ne diyor bu adam, ben anlamadım."),
    ("cidiyrum ben pazara, bişey ister misun getireyim", "Gidiyorum ben pazara, bir şey ister misin getireyim?"),
    ("pek güzel olmuş da bu yemek, eline sağluk", "Çok güzel olmuş bu yemek, eline sağlık."),
    ("noldi sana böyle, keyfun mu yok bugün uşağum", "Ne oldu sana böyle, keyfin mi yok bugün?"),
    ("baksana da bana, sen beni dinliy misun hiç", "Baksana bana, sen beni dinliyor musun hiç?"),
    ("he tamam anladum, yarın celirum o zaman", "Evet tamam anladım, yarın gelirim o zaman."),
    ("da nereye gidiysun bu saatte uşağum, dur biraz", "Nereye gidiyorsun bu saatte, dur biraz."),
    ("çayi demledum, gel de bir bardak iç bakalum", "Çayı demledim, gel de bir bardak iç bakalım."),
    ("iş bitti mi ha, akşama bize gelir misun sen", "İş bitti mi, akşama bize gelir misin sen?"),
    ("bu deniz pek soğuk da, girilmiy böyle havada", "Bu deniz çok soğuk, girilmiyor böyle havada."),
    ("ne yapaysun orda öyle, gel yardım et bana", "Ne yapıyorsun orada öyle, gel yardım et bana."),
    ("napıyon gari, geliyon mu bizim oraya akşama", "Ne yapıyorsun, geliyor musun bizim oraya akşama?"),
    ("baya yoruldum ya bugün, hadi ya artık eve gidek", "Çok yoruldum bugün, hadi artık eve gidelim."),
    ("ne diyon sen ya, ben ööle bişey demedim ki", "Ne diyorsun sen, ben öyle bir şey demedim ki."),
    ("gari kalk hadi, işe geç kalcan yine böyle", "Hadi kalk, işe geç kalacaksın yine böyle."),
    ("bakıyon mu şuna, resmen dalga geçiyo bizimle", "Bakıyor musun şuna, resmen dalga geçiyor bizimle."),
    ("hadi ya inanmıyom sana, doğru söyle bana gari", "Hadi inanmıyorum sana, doğru söyle bana."),
    ("bu sıcakta nası çalışıyon gari, yandım ben", "Bu sıcakta nasıl çalışıyorsun, yandım ben."),
    ("gel gari otur şuraya, çorba içtik mi biz", "Gel otur şuraya, çorba içelim mi biz?"),
    ("napcan şimdi ya, işler iyice karıştı gari", "Ne yapacaksın şimdi, işler iyice karıştı."),
    ("dur ya acele etme, hallolur o iş gari merak etme", "Dur acele etme, hallolur o iş merak etme."),
    ("napan qardaş, gelirem ben de oraya birazdan ha", "Ne yapıyorsun kardeşim, gelirim ben de oraya birazdan."),
    ("noldi bele, sen niye küstün bana emi", "Ne oldu böyle, sen niye küstün bana?"),
    ("giderem ben şimdi, sonra yaparam o işi merak etme", "Giderim ben şimdi, sonra yaparım o işi merak etme."),
    ("ne diyisen sen ya, ben anlamiram bu işi", "Ne diyorsun sen, ben anlamıyorum bu işi."),
    ("gel bıri, sana bişe diyecem kulağına be", "Gel buraya, sana bir şey diyeceğim kulağına."),
    ("bu iş bele olmaz, otur da konuşak biraz ha", "Bu iş böyle olmaz, otur da konuşalım biraz."),
    ("acıktım ben qardaş, yemek var mı bı yerde", "Acıktım ben kardeşim, yemek var mı bir yerde?"),
    ("naşisen bugün, keyfin yerinde mi bari emi", "Nasılsın bugün, keyfin yerinde mi bari?"),
    ("yaa napcaz şimdi, hiç param yok bu ay valla", "Ya ne yapacağız şimdi, hiç param yok bu ay."),
    ("gelcem dedim ya, niye sürekli soruyon aynı şeyi", "Geleceğim dedim ya, niye sürekli soruyorsun aynı şeyi?"),
    ("bilmiyom ki napcam, kafam çok karışık şu an", "Bilmiyorum ne yapacağım, kafam çok karışık şu an."),
    ("naptın lan sen, bütün planı bozdun resmen", "Ne yaptın sen, bütün planı bozdun resmen."),
    ("gidiyoz işte biz de, sen gelmicen mi bizimle", "Gidiyoruz işte biz de, sen gelmeyecek misin bizimle?"),
    ("çok saolun valla, çok yardımcı oldunuz bana", "Çok sağ olun, çok yardımcı oldunuz bana."),
    ("napıyosun kanki, müsait misin bi konuşcaz", "Ne yapıyorsun kanka, müsait misin bir konuşacağız?"),
    ("abi yapma ya, bu kadarı da olmaz artık gerçekten", "Abi yapma, bu kadarı da olmaz artık gerçekten."),
    ("valla bilemedim şimdi, bi düşüneyim de söylerim", "Vallahi bilemedim şimdi, bir düşüneyim de söylerim."),
    ("çok acıktım ya, bişeyler yesek mi acaba dışarda", "Çok acıktım, bir şeyler yesek mi acaba dışarıda?"),
    ("gelmiyo musun cidden, bak sonra pişman olursun ha", "Gelmiyor musun cidden, bak sonra pişman olursun."),
    ("ne alaka şimdi ya, ben öyle demek istemedim ki", "Ne alaka şimdi, ben öyle demek istemedim ki."),
    ("boşver ya takma kafana, düzelir o iş merak etme", "Boş ver takma kafana, düzelir o iş merak etme."),
    ("bekle bi saniye, hemen geliyom yanına ben", "Bekle bir saniye, hemen geliyorum yanına ben."),
    ("noorun gardaş, gel hele bi otur şuraya", "Ne yapıyorsun kardeşim, gel otur şuraya."),
    ("hindi çıkıyom evden, sen nörüsün bakem", "Şimdi çıkıyorum evden, sen nasılsın bakalım?"),
    ("masat yoruldum ula, baksana hele şu işe", "Çok yoruldum, baksana şu işe."),
    ("gel hele gayrı, yemek soğuyo bekliyoz seni", "Gel artık, yemek soğuyor bekliyoruz seni."),
    ("emmi bu yol nereye gidiyo, bi sorayım dedim", "Amca bu yol nereye gidiyor, bir sorayım dedim."),
    ("noorun bütün gün, hiç haber vermiyon bize", "Ne yapıyorsun bütün gün, hiç haber vermiyorsun bize?"),
    ("yav bırak şimdi onu, sonra hallederiz gayrı", "Ya bırak şimdi onu, sonra hallederiz."),
    ("hindi mi geldin, biz seni sabahtan bekliyoz", "Şimdi mi geldin, biz seni sabahtan bekliyoruz."),
    ("da uşağum n'apaysun orda, gel bize çıkalum yukarı", "Ne yapıyorsun orada, gel bize çıkalım yukarı."),
    ("balık tuttun mi bugün, akşama kızartalum da", "Balık tuttun mu bugün, akşama kızartalım."),
    ("çayi koydum sobaya, gel de içelim uşağum ha", "Çayı koydum sobaya, gel de içelim."),
    ("gari yeter ya, bu kadar da olmaz ki bak", "Yeter ya, bu kadar da olmaz ki bak."),
    ("napıyon orda gari, gel de yardım et bize ya", "Ne yapıyorsun orada, gel de yardım et bize."),
    ("baya güzel olmuş ya bu, eline sağlık gari", "Bayağı güzel olmuş bu, eline sağlık."),
    ("noldi qardaş, keyfin mi kaçtı bugün senin", "Ne oldu kardeşim, keyfin mi kaçtı bugün senin?"),
    ("gelirem ben de düğüne, sen merak etme hele", "Gelirim ben de düğüne, sen merak etme."),
    ("ne diyisen ya, ben hiç anlamiram bu işten", "Ne diyorsun, ben hiç anlamıyorum bu işten."),
    ("aga bu olay çok saçma ya, kafam almıyo resmen", "Abi bu olay çok saçma, kafam almıyor resmen."),
    ("valla helal olsun sana, tam adamısın bu işin", "Vallahi helal olsun sana, tam adamısın bu işin."),
    ("of ya sıkıldım baya, bi yerlere gidek mi akşam", "Of ya sıkıldım bayağı, bir yerlere gidelim mi akşam?"),
    ("kanka bu ne biçim iş ya, hiç beklemiyodum bunu", "Kanka bu ne biçim iş, hiç beklemiyordum bunu."),
    ("hadi len oradan, inanmıyom sana zerre kadar", "Hadi oradan, inanmıyorum sana zerre kadar."),
    ("ya boşver gitsin, kafaya takmaya değmez o kadar", "Ya boş ver gitsin, kafaya takmaya değmez o kadar."),
    ("bi dur ya nefes al, her şeyi büyütüyon gözünde", "Bir dur ya nefes al, her şeyi büyütüyorsun gözünde."),
]

SLANG_PAIRS = [
    ("slm nbr, bgn müsait misin bi ara konuşcaz", "Selam nasılsın, bugün müsait misin bir ara konuşacağız?"),
    ("tşk ederim abi, çok yardımcı oldun eyw", "Teşekkür ederim abi, çok yardımcı oldun eyvallah."),
    ("tmm anladım, grşrz o zaman kib", "Tamam anladım, görüşürüz o zaman kendine iyi bak."),
    ("knk sıkıntı yok, ben hallederim onu bzdn", "Kanka sorun yok, ben hallederim onu birazdan."),
    ("yok ya olmz, o kadar bekleyemem çok acil", "Yok ya olmaz, o kadar bekleyemem çok acil."),
    ("ig, şifremi unuttum, yenisini nasıl alcam", "İyi günler, şifremi unuttum, yenisini nasıl alacağım?"),
    ("dimi, ben de öyle düşünmüştüm zaten", "Değil mi, ben de öyle düşünmüştüm zaten."),
    ("ndmk şimdi bu, hiç anlamadım valla açıkçası", "Ne demek şimdi bu, hiç anlamadım açıkçası."),
    ("hcm bi el atsanıza şu işe, çok uzadı artık", "Hocam bir el atsanıza şu işe, çok uzadı artık."),
    ("slm abi, bu akşam maça gelio musun, bi haber ver", "Selam abi, bu akşam maça geliyor musun, bir haber ver."),
    ("cnm çok özledim seni, ne zmn görüşcez ya", "Canım çok özledim seni, ne zaman görüşeceğiz ya?"),
    ("tşkler valla, cidden çok iy oldu bu, kib", "Teşekkürler vallahi, cidden çok iyi oldu bu, kendine iyi bak."),
    ("nbr kanka, nvny bakalım, uzun oldu görüşmeyeli", "Nasılsın kanka, ne var ne yok bakalım, uzun oldu görüşmeyeli."),
    ("tmm o zmn ben gidio, snra ararım seni olr mu", "Tamam o zaman ben gidiyorum, sonra ararım seni olur mu?"),
    ("abi napıon ya, telefonu aç biraz, saatlerdir arıom", "Abi ne yapıyorsun ya, telefonu aç biraz, saatlerdir arıyorum."),
    ("slm, uygulama açılmıo sürekli hata verio napcam", "Selam, uygulama açılmıyor sürekli hata veriyor ne yapacağım?"),
    ("eyw reis, sorun çözüldü sonunda, çok saolun", "Eyvallah reis, sorun çözüldü sonunda, çok sağ olun."),
    ("knk bi el at şu ödeve ya, hiç anlamadım vlla", "Kanka bir el at şu ödeve ya, hiç anlamadım vallahi."),
    ("tmm tmm anladım, hemen yapıom o zmn merak etme", "Tamam tamam anladım, hemen yapıyorum o zaman merak etme."),
    ("nbr moruk, bu akşam dışarı çıkıo muyuz ya", "Naber moruk, bu akşam dışarı çıkıyor muyuz ya?"),
    ("hcm slm, dersin kaçta başlıo bgn haberim yok", "Hocam selam, dersin kaçta başlıyor bugün haberim yok."),
    ("aynn haklısın ya, ben de aynı şeyi düşünüyodum msl", "Aynen haklısın ya, ben de aynı şeyi düşünüyordum mesela."),
    ("bşver ya takma, düzelir o iş bzdn merak etme sn", "Boş ver ya takma, düzelir o iş birazdan merak etme sen."),
    ("cnm ya çok özledim, ne zmn geliyon buraya söyle", "Canım ya çok özledim, ne zaman geliyorsun buraya söyle."),
    ("valla süpr olmuş, eline sağlık kanka harika ya", "Vallahi süper olmuş, eline sağlık kanka harika ya."),
    ("abi napıyon, telefonu hiç açmıyon 2 saattir arıom", "Abi ne yapıyorsun, telefonu hiç açmıyorsun iki saattir arıyorum."),
]

def all_pairs():
    out = []
    for s, t in DIALECT_PAIRS:
        out.append((s, t, "dialect_llm", ""))
    for s, t in SLANG_PAIRS:
        out.append((s, t, "slang_llm", ""))
    return out

if __name__ == "__main__":
    c = all_pairs()
    print(f"Hand-written pairs: {len(c)} (dialect {len(DIALECT_PAIRS)} + slang {len(SLANG_PAIRS)})")
    print(f"Slang-heavy clean seeds: {len(SLANG_CLEAN_SEEDS)}")
