
JARGON = {
    "selam":"slm","selamlar":"slmlr","merhaba":"mrb","merhabalar":"mrblr",
    "günaydın":"gnydn","iyi günler":"ig","iyi akşamlar":"ia","iyi geceler":"igg",
    "nasılsın":"nbr","nasılsınız":"nbr","naber":"nbr","ne haber":"nbr",
    "kanka":"knk","abi":"abi","reis":"reis",
    "canım":"cnm","hocam":"hcm","dostum":"dostum","moruk":"moruk",
    "teşekkürler":"tşk","teşekkür ederim":"tşk ederim","teşekkür":"tşk",
    "sağ ol":"sağol","sağ olun":"sağolun","rica ederim":"rica","eyvallah":"eyw",
    "tamam":"tmm","tamamdır":"tmmdr","aynen":"aynn","kesinlikle":"kesin",
    "peki":"pk","olur":"olr","tabii":"tbi","tabii ki":"tbiki","elbette":"elbet",
    "evet":"e","hayır":"yok","yok artık":"yok arttık","olmaz":"olmz",
    "boş ver":"bşver","her neyse":"neyse","ne bileyim":"nbliyim",
    "bugün":"bgn","şimdi":"şmdi","şu an":"şuan","şu anda":"şuan","yani":"yni",
    "çünkü":"cnki","gerçekten":"grçkten","mesela":"msl","acaba":"acb",
    "bir dakika":"bi dk","birazdan":"bzdn","az önce":"az önce","hemen":"hmn",
    "bilmiyorum":"bilmiom","biliyorum":"biliom","görüşürüz":"grşrz",
    "inşallah":"inş","maşallah":"maşş","değil mi":"dimi","ne demek":"ndmk",
    "kendine iyi bak":"kib","çok güzel":"çokgzl","çok teşekkürler":"çoktşk",
    "rica ederim":"ricam","estağfurullah":"estf","allah allah":"aaa",
    "problem":"sıkıntı","problem değil":"sıkıntı yok","sorun":"sıkıntı",
    "internet":"net","bağlantı":"baglanti","numara":"no","telefon":"tel",
    "mesaj":"msj","fotoğraf":"foto","fotoğrafı":"fotoyu","video":"vidyo",
    "uygulama":"app","hesap":"hesap","şifre":"şifre",
    "abla":"abla","abi":"abi","kanka":"knk","dostum":"dosto",
    "vallahi":"valla","yemin ederim":"yemin","gerçekten mi":"cidden mi","cidden":"cidden",
    "bu arada":"ba","her neyse":"nvm","neyse":"nyse","şaka şaka":"şşş",
    "çok komik":"çk kmk","çok iyi":"çok iy","süper":"süpr","harika":"hrk","muhteşem":"mükemmel",
    "bekle":"bkle","bekliyorum":"bekliom","geliyorum":"gelio","gidiyorum":"gidio",
    "yapıyorum":"yapıo","napıyorsun":"napıon","ne yapıyorsun":"napıon",
    "anladım":"anld","anlamadım":"anlmdm","bilmiyorum":"blmyrm","biliyorum":"bliyrm",
    "tamam mı":"tmm mı","olur mu":"olrmu","değil mi":"dimi","ne zaman":"nzmn",
    "nerede":"nrde","nereye":"nereye","niye":"niye","neden":"nedn","nasıl":"nsl",
    "para":"para","zaman":"zmn","mesaj at":"mesaj at","arıyorum":"arıom",
    "merhaba":"mrb","selamün aleyküm":"sea","aleyküm selam":"as","hoşça kal":"hşçkl",
    "iyiyim sen":"iyiyim sen","sen nasılsın":"snnbr","ne var ne yok":"nvny",
    "bir saniye":"1sn","iki dakika":"2dk","biraz":"bzck","çabuk":"çbk","acele":"acele",
    "lütfen":"lütfen","rica etsem":"ricm","yardım":"yrdm","yardımcı ol":"yrdm et",
}

DIALECT_GENERAL_RULES = [
    (r"(a|ı)yorum\b", r"\1yom"), (r"(e|i)yorum\b", r"\1yom"),
    (r"(o|u)yorum\b", r"\1yom"), (r"(ö|ü)yorum\b", r"\1yom"),
    (r"(a|ı)yorsun\b", r"\1yon"), (r"(e|i)yorsun\b", r"\1yon"),
    (r"(o|u)yorsun\b", r"\1yon"), (r"(ö|ü)yorsun\b", r"\1yon"),
    (r"(a|ı|e|i|o|u|ö|ü)yoruz\b", r"\1yoz"),
    (r"(a|ı|e|i|o|u|ö|ü)yorlar\b", r"\1yolar"),
    (r"(a|ı|e|i|o|u|ö|ü)yor\b", r"\1yo"),
    (r"eceğim\b","cem"),(r"acağım\b","cam"),(r"eceğiz\b","cez"),(r"acağız\b","caz"),
    (r"eceksin\b","cen"),(r"acaksın\b","can"),(r"eceksin\b","cen"),
    (r"ecek\b","cek"),(r"acak\b","cak"),
    (r"\bdeğil\b","diil"),(r"\bdeğilim\b","diilim"),(r"\bdeğil mi\b","dimi"),
    (r"\bbir\b","bi"),(r"\bne yapıyorsun\b","napıyon"),(r"\bne yapıyor\b","napıyo"),
    (r"\bnasılsın\b","nassın"),(r"\bne oldu\b","noldu"),(r"\bne olacak\b","nolcak"),
    (r"\bşöyle\b","şööle"),(r"\bböyle\b","bööle"),(r"\biçin\b","icin"),
]
DIALECT_BLACKSEA_RULES = [
    (r"(i|ı)yorum\b", r"\1yrum"),(r"(u|ü)yorum\b", r"\1yrum"),
    (r"(i|ı)yorsun\b", r"\1ysun"),(r"(i|ı)yor\b", r"\1y"),
    (r"\bgeliyorum\b","celiyrum"),(r"\bgidiyorum\b","cidiyrum"),
    (r"\bne yapıyorsun\b","n'apaysun"),(r"\bnasılsın\b","nasunuz"),
    (r"\bdeğil\b","deel"),(r"\bmısın\b","misun"),(r"\bmisin\b","misun"),
    (r"\bmusun\b","misun"),(r"\bevet\b","he"),(r"\bçok\b","pek"),
    (r"\bne oldu\b","n'oldi"),(r"\bbak\b","bak da"),
]
DIALECT_AEGEAN_RULES = [
    (r"(a|ı|o|u)yor musun\b", r"\1yon mu"),(r"(e|i|ö|ü)yor musun\b", r"\1yon mu"),
    (r"(a|ı|o|u)yorsun\b", r"\1yon"),(r"(e|i|ö|ü)yorsun\b", r"\1yon"),
    (r"(a|ı|e|i|o|u|ö|ü)yor\b", r"\1yo"),
    (r"\bne yapıyorsun\b","napıyon gari"),(r"\btamam\b","hadi ya"),
    (r"\bçok\b","baya"),(r"\bçocuk\b","gari"),
]
DIALECT_EAST_RULES = [
    (r"(i|ı)yorum\b","irem"),(r"(u|ü)yorum\b","urem"),
    (r"\bgeliyorum\b","gelirem"),(r"\bgidiyorum\b","giderem"),
    (r"\byaparım\b","yaparam"),(r"\bne yapıyorsun\b","napan"),
    (r"\bne oldu\b","noldi"),(r"\bböyle\b","bele"),
    (r"\bmısın\b","misen"),(r"\bmisin\b","misen"),(r"\byapacağım\b","yapacam ha"),
]
DIALECT_CENTRAL_ANATOLIA_RULES = [
    (r"(a|ı)yorum\b", r"\1yiyom"),(r"(e|i)yorum\b", r"\1yiyom"),
    (r"(a|ı)yorsun\b", r"\1yon"),(r"(e|i)yorsun\b", r"\1yon"),
    (r"(a|ı|e|i|o|u|ö|ü)yor\b", r"\1yo"),
    (r"\bgeliyorum\b","geliyom"),(r"\bgidiyorum\b","gidiyom"),
    (r"\bne yapıyorsun\b","noorun"),(r"\bnasılsın\b","nörüsün"),
    (r"\bgel\b","gel hele"),(r"\bbak\b","baksana hele"),
    (r"\bşimdi\b","hindi"),(r"\bböyle\b","böyük"),(r"\bçok\b","masat"),
]
DIALECT_RULES = {
    "general":DIALECT_GENERAL_RULES,"blacksea":DIALECT_BLACKSEA_RULES,
    "aegean":DIALECT_AEGEAN_RULES,"east":DIALECT_EAST_RULES,"central_anatolia":DIALECT_CENTRAL_ANATOLIA_RULES,
}
DIALECT_TAILS = {
    "general":["","","ya","işte","ki"],
    "blacksea":["uşağum","da","ha"," da","haçan"],
    "aegean":["gari","ya","he mi","hadi"],
    "east":["ha","ya","be","emi"],
    "central_anatolia":["hele","gayrı","emmi","ula","yav"],
}
